name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Extract commit SHA
    #   id: vars
    #   run: echo "::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})"

    - name: Generate Short Commit SHA
      run: echo "COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: saikumar-tv/test
        token: ${{ secrets.PAT_TOKEN }}
        path: test

    - name: Update values.yml
      run: |
        sed -i 's|image: .*|image: ${{env.COMMIT_SHA}}|' test/test-service/test-curl.yml
        cat test/test-service/test-curl.yml

    - name: Commit and push changes
      run: |
        cd test
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add test-service/test-curl.yml
        git commit -m "Update image tag to ${{ steps.vars.outputs.short_sha }}"
        git push
