name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Extract commit SHA
    #   id: vars
    #   run: echo "::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})"

    - name: Generate Short Commit SHA
      run: echo "COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Get latest commit message
      id: commit_message
      run: echo "LATEST_COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: saikumar-tv/test
        token: ${{ secrets.PAT_TOKEN }}
        path: test

    - name: Update values.yml
      run: |
        sed -i 's|image: .*|image: ${{env.COMMIT_SHA}}|' test/test-service/test-curl.yml
        cat test/test-service/test-curl.yml

    - name: Commit and push changes
      run: |
        cd test
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add test-service/test-curl.yml
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update image tag to ${{ env.COMMIT_SHA }} - ${{ env.LATEST_COMMIT_MSG }}"
          git push
        else
          echo "No changes to commit"
        fi
        
